name: Extract git metrics

on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to extract metrics
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract metrics
        id: extract_metrics
        uses: avaliasystems/gh-actions-git-metrics@main
        with:
          who-to-greet: 'Olivier'
      # Use the output from the `hello` step
#      - name: Get the output time
#        run: echo "The time was ${{ steps.extract_metrics.outputs.time }}"
      - name: Commit files
        run: |
          git log -C $GITHUB_WORKSPACE --no-merges
          echo "commit files, checking..."
          pwd
          ls -al 
          find output
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"
          git status
          git add --all
          git commit -m "Update git metrics"
          git push 

